<?xml version="1.0" encoding="utf-8"?><Database Name="QL_CHDT" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-96MF1DFE;Initial Catalog=QL_CHDT;Integrated Security=True" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="QL_CHDTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETHD" Member="CHITIETHDs">
    <Type Name="CHITIETHD">
      <Column Name="MaCTHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHD" Member="HOADON" ThisKey="MaHD" OtherKey="MaHD" Type="HOADON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONGSOKYTHUAT" Member="THONGSOKYTHUATs">
    <Type Name="THONGSOKYTHUAT">
      <Column Name="MaTS" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ManHinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CameraSau" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cameratruoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Ram" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Rom" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pin" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HDH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="SANPHAM_THONGSOKYTHUAT" Member="SANPHAM" ThisKey="MaHang" OtherKey="MaHang" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenKhach" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayBan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHD" Member="CHITIETHDs" ThisKey="MaHD" OtherKey="MaHD" Type="CHITIETHD" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MaHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HangSX" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SANPHAM_THONGSOKYTHUAT" Member="THONGSOKYTHUATs" ThisKey="MaHang" OtherKey="MaHang" Type="THONGSOKYTHUAT" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Pass" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="Gioitinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Quyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>